### ISSUE TITLE
Unknown type "XOpenCTIIncident"

### ISSUE THREAD

**Issue by phdowling** [amr-cossi/opencti-maltego#11]
Getting this from the search transforms:

```
INFO:root:Listing StixCyberObservables with filters null.
DEBUG:urllib3.connectionpool:Resetting dropped connection: demo.opencti.io
DEBUG:urllib3.connectionpool:https://demo.opencti.io:443 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Stix-Domain-Objects with filters null.
DEBUG:urllib3.connectionpool:Resetting dropped connection: demo.opencti.io
DEBUG:urllib3.connectionpool:https://demo.opencti.io:443 "POST /graphql HTTP/1.1" 200 None
ERROR:root:Unknown type "XOpenCTIIncident". Did you mean "XOpenCTIText" or "XOpenCTIUserAgent"?
ERROR:maltego.server:An exception occurred while executing your transform code.
ERROR:maltego.server:{'name': 'Unknown type "XOpenCTIIncident". Did you mean "XOpenCTIText" or "XOpenCTIUserAgent"?', 'message': 'Unknown type "XOpenCTIIncident". Did you mean "XOpenCTIText" or "XOpenCTIUserAgent"?'}
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/maltego_trx/server.py", line 45, in run_transform
return transform_method.run_transform(client_msg), 200 # Transform class
File "/usr/local/lib/python3.8/site-packages/maltego_trx/transform.py", line 12, in run_transform
cls.create_entities(request, response)
File "/var/www/TRX/transforms/openctimaltegophrasePlainSearch.py", line 12, in create_entities
opencti_transform("PlainSearch", None, request, response)
File "/var/www/TRX/opencti/openctitransform.py", line 62, in opencti_transform
plainSearchAndAddEntities(
File "/var/www/TRX/opencti/addEntities.py", line 166, in plainSearchAndAddEntities
opencti_domain_entities = opencti_api_client.stix_domain_object.list(
File "/usr/local/lib/python3.8/site-packages/pycti/entities/opencti_stix_domain_object.py", line 432, in list
result = self.opencti.query(
File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 279, in query
raise ValueError(
ValueError: {'name': 'Unknown type "XOpenCTIIncident". Did you mean "XOpenCTIText" or "XOpenCTIUserAgent"?', 'message': 'Unknown type "XOpenCTIIncident". Did you mean "XOpenCTIText" or "XOpenCTIUserAgent"?'}
```
I am guessing this is an update to OpenCTI or PyCTI regarding the new incident entity? Anything we can/should do on the Transform side to fix?

**Comment by amr-cossi** [comment]
OpenCTI is migrating to the new STIX2.1 Incident entity without ensuring backward compatibility in API calls or Pycti.
As the demo is deployed on the rolling version of OpenCTI, it is now in the not-yet-released 4.5.0 with this change in effect while this repository is not yet compatible with it.

This change is already handled in maltego-stix2 and prepared in opencti-maltego: 
 - https://github.com/amr-cossi/opencti-maltego/blob/8700baf92a1a28aadccef6d974088b81a326c31c/trx/gunicorn/opencti/addEntities.py#L76
 - https://github.com/amr-cossi/opencti-maltego/blob/8700baf92a1a28aadccef6d974088b81a326c31c/trx/gunicorn/opencti/addEntities.py#L178
 - https://github.com/amr-cossi/opencti-maltego/blob/8700baf92a1a28aadccef6d974088b81a326c31c/trx/gunicorn/opencti/openctitransform.py#L91
 - https://github.com/amr-cossi/opencti-maltego/blob/8700baf92a1a28aadccef6d974088b81a326c31c/trx/gunicorn/opencti/utils.py#L85

But the real question is : should this integration be compatible with only the lastest version of OpenCTI or as many versions as possible ? Nothing is done today to be compatible with more than one version.

**Comment by amr-cossi** [comment]
And the issue is worse on your side with a server integration because when users are deploying their own infra, they can choose a version of pycti and a version of this repository compatible with their current OpenCTI (and we should at least show in the Readme or in the releases the full list of compatible versions), but your server deployment needs to be able to query various instances with different versions.

**Comment by phdowling** [comment]
@amr-cossi I think we want to aim for broad support, but not supporting the demo instance is also not ideal since it's the natural starting point for most users - is there something we can do to play nice both with the demo instance and older instances? Or any particular version of OpenCTI we should be aiming to support? CC'ing @SamuelHassine on this discussion since he may have some insight for us.

**Comment by phdowling** [comment]
Actually, can we make the server version an optional transform setting / config item? That would make sense in both the local and remote settings.

**Comment by amr-cossi** [comment]
According to @SamuelHassine, backward compatibility should be better handled in pycti starting with 4.5.0. But up to now, you have to install the pycti version specific to the OpenCTI instance you query. So even with a parameter in the config and some if/else in the code, it won't be possible to easily query an OpenCTI 4.4.X and a 4.5.X with the same version of pycti installed.
Is it possible on your side to run a completely different integration based on a parameter (to have several pycti versions running on the server side at the same time) ?

Otherwise I think we need to wait for the 4.5.0 release, adapt the code to be compatible with OpenCTI >= 4.5.0 only, keep a tag as of today for people using 4.3 - 4.4 versions, and make sure for future versions that backward compatibility is provided by both pycti and this code.

**Comment by amr-cossi** [comment]
Fixed, the last version is compatible with Incidents in the future v4.5.0
